[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quantum-rtsc-protocol"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["numpy","scipy","pandas","matplotlib","gdspy","typer","rich"]
