[build-system]\nrequires = [\
setuptools>=68\, \wheel\]\nbuild-backend = \setuptools.build_meta\\n\n[project]\nname = \quantum-rtsc-protocol\\nversion = \0.1.0\\nrequires-python = \>=3.9\\ndependencies = [\numpy\,\scipy\,\pandas\,\matplotlib\,\gdspy\,\typer\,\rich\]
