name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg   # headless matplotlib

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run unit tests
      run: pytest -q

    - name: Run demo pipeline
      run: |
        make demo
        test -s out/demo/rtsc_results.json
        test -s out/demo/rtsc_analysis_report.md
        test -s out/demo/rtsc_analysis_dashboard.png
        python - << 'PY'
        import json, sys
        d = json.load(open('out/demo/rtsc_results.json'))
        assert 'timestamp' in d and 'tc_estimate_K' in d and 'success_probability' in d
        PY

    - name: Upload demo artifacts
      uses: actions/upload-artifact@v4
      with:
        name: demo-artifacts
        path: out/demo/**
