name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest

    - name: Run demo pipeline
      run: |
        make demo
        test -s out/demo/rtsc_results.json
        test -s out/demo/rtsc_analysis_report.md
        test -s out/demo/rtsc_analysis_dashboard.png
        python -c "import json; d=json.load(open('out/demo/rtsc_results.json')); assert 'timestamp' in d and 'tc_estimate_K' in d and 'success_probability' in d"

    - name: Upload demo artifacts
      uses: actions/upload-artifact@v3
      with:
        name: demo-artifacts
        path: out/demo/**
