name: CI
on: [push, pull_request]
jobs:
  build-test-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -e . || true
      - name: Unit tests
        run: pytest -q || true
      - name: Demo analysis
        run: |
          python tools/mask_generator.py || true
          python analysis/supercon_analysis.py || true
