name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: pytest -q

      # Prefer calling the pipeline module directly; fallback to Makefile
      - name: Build demo artifacts
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p out/demo
          python - <<'PY'
          import sys, pathlib
          out = pathlib.Path("out/demo")
          out.mkdir(parents=True, exist_ok=True)
          # Try package module first, fallback import path
          try:
              from quantum_rtsc_protocol.tools.rtsc_pipeline import main as run
          except Exception:
              import importlib.util, os
              spec = importlib.util.spec_from_file_location(
                  "rtsc_pipeline", "quantum_rtsc_protocol/tools/rtsc_pipeline.py"
              )
              mod = importlib.util.module_from_spec(spec)
              spec.loader.exec_module(mod)  # type: ignore
              run = mod.main
          sys.argv = ["rtsc_pipeline", "--demo", "--out", str(out)]
          run()
          PY
          test -s out/demo/rtsc_results.json
          test -s out/demo/rtsc_analysis_report.md
          test -s out/demo/rtsc_analysis_dashboard.png
          python - <<'PY'
          import json; d=json.load(open('out/demo/rtsc_results.json'))
          assert 'timestamp' in d and 'tc_estimate_K' in d and 'success_probability' in d
          PY

      - name: Upload demo artifacts
        uses: actions/upload-artifact@v4
        with:
          name: demo-artifacts
          path: out/demo/**
